"""empty message

Revision ID: 663f9a8e82a4
Revises: 434759965d19
Create Date: 2018-02-12 18:46:24.841600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663f9a8e82a4'
down_revision = '434759965d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('report_type', sa.Enum('table', 'graph', 'chart', name='reporttypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
