"""empty message

Revision ID: daae827918ee
Revises: ea81d087c518
Create Date: 2018-02-19 20:08:35.187176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daae827918ee'
down_revision = 'ea81d087c518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('column_id', sa.BigInteger(), nullable=True),
    sa.Column('foreign_column_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['foreign_column_id'], ['columns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('column_id', 'foreign_column_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foreign_keys')
    # ### end Alembic commands ###
