"""empty message

Revision ID: ea81d087c518
Revises: 663f9a8e82a4
Create Date: 2018-02-18 19:45:28.944747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea81d087c518'
down_revision = '663f9a8e82a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema', 'name', name='_schema_name_uc')
    )
    op.create_table('columns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='_table_name_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('columns')
    op.drop_table('tables')
    # ### end Alembic commands ###
